apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldnode
  labels:
    app: helloworldnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworldnode
  template:
    metadata:
      labels:
        app: helloworldnode
    spec:
      containers:
      - name: helloworldnode
        image: gcr.io/tecklearn/helloworldnode:latest
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: helloworldnode
spec:
  selector:
    app: helloworldnode
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer